### ISSUE TITLE
[Feature request] Collapse child prompts

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#10]
Could you make it so that you can hide the child prompts by clicking something like an arrow next to the parent prompt?

![image](https://user-images.githubusercontent.com/48849652/208212490-1c829036-5452-47ff-b73f-b9adf4f36ef4.png)

I currently have about 40 child prompts in that "Myne", and it adds quite a lot to the scrolling time.

V0.9.0

**Comment by Snowad14** [comment]
added in 1.0.0
