### ISSUE TITLE
[Feature request] Some small quality of life improvements

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#11]
**Minor changes for when you are bored.**

1. You cannot currently click a child prompt before you select the parent prompt. It would be good if it automatically selected the parent prompt in that situation.

2. _"New project"_ button, if you want to clear everything. On top of the folder bar would probably be good. Make sure you add a confirmation popup.

3. The search does not display child prompts, only parent prompts. It could be good if it displayed both the child and the parent in that situation.

4. Replace "Are you sure you want to delete this prompt?" with "Are you sure you want to delete this prompt from 32 images?" when deleting a prompt.

5. Add a gray _"Search prompts..."_ text or a search magnifying glass in the search bars. They look like just strange white bars at the moment.

6. Hide the arrow on parent prompts that do not have child prompts. They only confuse you now.

7. There's quite a lot of empty space in here. You could grow the prompt field a bit or add more buttons on the top.

![image](https://user-images.githubusercontent.com/48849652/208266074-5bb70699-a430-474f-965c-69aca56d87fc.png)

V1.0.0

**Comment by Snowad14** [comment]
I did all of them except 2. and 7, I will see later
