### ISSUE TITLE
[Minor feature request] Storing settings

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#12]
If you were to write a .ini file (or .conf or .cfg or whatever, fancy words for text files) on launch, you could use it to store and load any settings used previously for use next time. Things like last folder used (don't need to auto-open it, just have the browse button open the last browsed folder in previous session, so that you don't need to look for it), the checkbox settings and the seperation symbols could all be stored in the .ini file.

It might be worthwhile to store it in a folder somewhere away from the .exe so that it doesn't get deleted when you update BatchPrompter and can therefore be loaded in the next version as well.

Not a very important update, just a small quality of life one. The prompt editing is a lot more important in my opinion, so if you could get that working, I would appreciate it. :)
Sorry for demanding so much. This application will be quite good in any future portfolio though, so remember to include it when trying to showcase your skills.

V1.0.1

**Comment by Snowad14** [comment]
saved as BatchPrompter.cfg in appdata folder
