### ISSUE TITLE
[Feature request] Coloured backgrounds for selected child prompts

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#14]
Since the picture backgrounds are red if the parent prompt is in the picture, how about turning it blue or something if the selected child prompts are also in the picture?

![Untitled-3](https://user-images.githubusercontent.com/48849652/211201795-e9e7ac70-dd43-43e9-b9c4-8a87faaf90d3.png)

V1.1.1

**Comment by Snowad14** [comment]
others background colors is far too disturbing 
I add it but I may delete it later
