### ISSUE TITLE
[Feature Request] Image dropdown menu

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#3]
Could it be possible to make right clicking an image open a dropdown menu (like a normal right click), where you can select things like:

> _Open image_
> _Copy child prompts:_
>  ├ _Myne_
>  ├ _Benno_
>  └ _Lutz_

V0.8.4

**Comment by Juusoz** [comment]
Two more things to add to the image dropdown menu:

> Add child prompt to:
>  ├ Myne
>  │ ├ baptism
>  │ ├ pajamas
>  │ └ business (list of Myne's unused child prompts)
>  ├ Benno
>  └ Lutz

> Remove child prompt from:
>  ├ Myne
>  │ ├ blushing
>  │ ├ eyes closed
>  │ └ no apron (list of Myne's used child prompts)
>  ├ Benno
>  └ Lutz

**Comment by Snowad14** [comment]
Copy child prompts a bit useless

**Comment by Juusoz** [comment]
> Copy child prompts a bit useless

Yeah, maybe a bit now, now that the "add child prompt" works. I had it previously just so you could add one or two child prompts to the parent prompt.

Gonna close this for you.
