### ISSUE TITLE
[Feature Request] Import image captions

### ISSUE THREAD

**Issue by Juusoz** [Snowad14/BatchPrompter#4]
Right now, BatchPrompter technically does not save the progress you've done, so unless if you are working on very small samples at a time, you will never be able to get all of the images prompted in one go.

So, just import the captions from the images. How hard could that be?
(We both know the answer to that one.)

V0.8.4

**Comment by Snowad14** [comment]
Import finished, you still have to test it to be sure that everything works. The import of the images put in the random order will be opened in this random order
